version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.7
        auth:
          username: ybooks
          password: $DOCKER_TOKEN # context / project UI env-var reference
    
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      # ... steps for building/testing app ...


      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=v0.1.$CIRCLE_BUILD_NUM
          PROJECT=ybooks/operator-redis-demo
          docker build -t $PROJECT:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $PROJECT:$TAG