# permissions for end users to edit jamesredis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jamesredis-editor-role
rules:
- apiGroups:
  - dev.ybooks240.github.com
  resources:
  - jamesredis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dev.ybooks240.github.com
  resources:
  - jamesredis/status
  verbs:
  - get
