# permissions for end users to view jamesredis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jamesredis-viewer-role
rules:
- apiGroups:
  - dev.ybooks240.github.com
  resources:
  - jamesredis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dev.ybooks240.github.com
  resources:
  - jamesredis/status
  verbs:
  - get
