apiVersion: dev.ybooks240.github.com/v1
kind: JamesRedis
metadata:
  name: jamesredis-sample
spec:
  replicas: 1
  image: redis:5.0.4
  config_map_name: redis-config

#  command:
#    - redis-server
#    - "/redis-master/redis.conf"
#        ports:
#        - containerPort: 6379
#        resources:
#          limits:
#            cpu: "0.1"
    # env:
    # - name: MASTER
    #   value: "true"
    # volumeMounts:
    # - mountPath: /redis-master-data
    #   name: data
    # - mountPath: /redis-master
    #   name: config
  # volumes:
  #   - name: data
  #     emptyDir: {}
  #   - name: config
  #     configMap:
  #       name: example-redis-config
  #       items:
  #       - key: redis-config
  #         path: redis.conf
